version: '3.4'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "schematesting_2"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3307:3306
    networks:
      - app-network

  nodejs:
    image: nodejs
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
    networks:
      - app-network

networks:
    app-network:
        driver: bridge